# Generated by Django 4.1.2 on 2022-10-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='resume',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
