# Generated by Django 4.1.2 on 2022-10-27 03:17

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='resume',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
